server {
    listen 80;
    server_name localhost;

    # 1. GESTIONE API (Deve essere precisa)
    location /api/ {
        # 'proxy_pass' punta al BE sulla porta 8000 via localhost
        proxy_pass http://127.0.0.1:8000/; 
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # 2. GESTIONE FRONTEND (React)
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # Questa riga serve per far funzionare il routing di React (es. react-router)
        # Se Nginx non trova il file, rimanda a index.html
        try_files $uri $uri/ /index.html;
    }
}